version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: docker/node.Dockerfile
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
  redis:
    build:
      context: ./
      dockerfile: redis.Dockerfile
    volumes:
      - './redis:/data'

# networks:
#   default:
#     external:
#       name: badurl_default
