version: '3'
services:
  redis:
    build:
      context: ./
      dockerfile: redis.Dockerfile
    volumes:
      - './redis:/data'

# networks:
#   default:
#     external:
#       name: badurl_default
